# Generated by Django 3.2.7 on 2021-10-01 04:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('ID', models.IntegerField(default=1633064181876673, editable=False, primary_key=True, serialize=False)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=128)),
                ('Image', models.ImageField(blank=True, upload_to=api.models.ContactImage)),
                ('Bug_FeedBack_Query', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('ID', models.IntegerField(default=1633064181876673, editable=False, primary_key=True, serialize=False)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('DiseaseName', models.CharField(max_length=512)),
                ('Percentage', models.CharField(max_length=128)),
                ('UploadedImage', models.ImageField(upload_to=api.models.UploadedImageName)),
                ('ProcessedColoredImage', models.ImageField(upload_to=api.models.processedColoredImageName)),
                ('boundingBoxImage', models.ImageField(upload_to=api.models.BoundingBoxImageName)),
                ('Remarks', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
